language: python
cache: pip

install:
    - pip install lektor
    - openssl aes-256-cbc -K $encrypted_1a75d1fe4feb_key -iv $encrypted_1a75d1fe4feb_iv -in uberspace-key.enc -out uberspace-key -d
    - cp known_hosts ~/.ssh/known_hosts
script:
    - lektor deploy --key-file uberspace-key
